version: "3.7"
services:
  front_dev:
    build:
      context: .
      dockerfile: Dockerfile
    command: sh -c "HOST='0.0.0.0' PORT=3000 npm run start"
    ports:
      - 3000:3000
    restart: on-failure

